---
# node-service
dist: trusty
language: python
sudo: required
before_script:
  - travis-tools/bin/report-travis-tools-version
  - export REPO_TYPE=`cat .travis-tools/repo-type`
  - export REPO_NAME="${TRAVIS_REPO_SLUG/#AverInformatics\//}"
  - export BUILD_DATETIME=`date -u '+%Y%m%d-%H%M%S'`
  - export BRANCH="${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}"
  - travis-tools/bin/upgrade-docker
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - pip install awscli --quiet
  - docker network create averdev
  - aws configure set region us-east-1
  - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
script:
  - npm run build
  - npm run --silent test
  - npm run --silent lint
  - mkdir -p context && cp Dockerfile.prod context/Dockerfile && cp -a dist context
  - docker build --squash -t "aver/${REPO_NAME}:${TRAVIS_BRANCH}.latest" -t "aver/${REPO_NAME}:${TRAVIS_COMMIT}" -t "aver/${REPO_NAME}:${TRAVIS_COMMIT}-${BUILD_DATETIME}" context
  - docker push aver/${REPO_NAME}:${TRAVIS_COMMIT}-${BUILD_DATETIME}
  - travis-tools/bin/register-build
after_success:
  - docker push aver/${REPO_NAME}:${TRAVIS_COMMIT}
  - docker push aver/${REPO_NAME}:${TRAVIS_BRANCH}.latest
  - travis-tools/bin/autorelease
notifications:
  slack: averinc:oda6ZyM5FuBEbIpW4y7XdAMT
