version: '2'

networks:
    default:
        external:
            name: averdev

services:
  corey-app-web:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    environment:
      - SOURCEMAPS
      - UGLIFY
    volumes:
      - .:/code
      - /code/node_modules
    command: [npm, run, start-native]
